scram::mef::PeriodicTest Class Reference
scram::mef::PeriodicTest Class Reference
Periodic test with 3 phases: deploy, test, functioning.
#include <exponential.h>
Public Member Functions
PeriodicTest (const ExpressionPtr &lambda, const ExpressionPtr &tau, const ExpressionPtr &theta, const ExpressionPtr &time)
Periodic tests with tests and repairs instantaneous and always successful.
PeriodicTest (const ExpressionPtr &lambda, const ExpressionPtr &mu, const ExpressionPtr &tau, const ExpressionPtr &theta, const ExpressionPtr &time)
Periodic tests with tests instantaneous and always successful.
PeriodicTest (const ExpressionPtr &lambda, const ExpressionPtr &lambda_test, const ExpressionPtr &mu, const ExpressionPtr &tau, const ExpressionPtr &theta, const ExpressionPtr &gamma, const ExpressionPtr &test_duration, const ExpressionPtr &available_at_test, const ExpressionPtr &sigma, const ExpressionPtr &omega, const ExpressionPtr &time)
Fully parametrized periodic-test description.
void Validate () const override
Validates the expression.
double Mean () noexceptoverride
double Max () noexceptoverride
double Min () noexceptoverride
Public Member Functions inherited from scram::mef::Expression
Expression (std::vector< ExpressionPtr > args={})
Constructor for use by derived classes to register their arguments.
const std::vector< ExpressionPtr > & args () const
double Sample () noexcept
virtual void Reset () noexcept
This routine resets the sampling to get new values.
virtual bool IsDeviate () noexcept
Determines if the value of the expression contains deviate expressions.
Additional Inherited Members
Protected Member Functions inherited from scram::mef::Expression
void AddArg (const ExpressionPtr &arg)
Registers an additional argument expression.
Detailed Description
Periodic test with 3 phases: deploy, test, functioning.
Definition at line 115 of file exponential.h.
Constructor & Destructor Documentation
scram::mef::PeriodicTest::PeriodicTest (const ExpressionPtr & lambda, const ExpressionPtr & tau, const ExpressionPtr & theta, const ExpressionPtr & time)
Periodic tests with tests and repairs instantaneous and always successful.
Parameters
[in] lambda The failure rate (hourly) when functioning.
[in] tau The time between tests in hours.
[in] theta The time before the first test in hours.
[in] time The current mission time in hours.
Definition at line 172 of file exponential.cc.
scram::mef::PeriodicTest::PeriodicTest (const ExpressionPtr & lambda, const ExpressionPtr & mu, const ExpressionPtr & tau, const ExpressionPtr & theta, const ExpressionPtr & time)
Periodic tests with tests instantaneous and always successful.
Parameters
[in] lambda The failure rate (hourly) when functioning.
[in] tau The time between tests in hours.
[in] theta The time before the first test in hours.
[in] time The current mission time in hours.
[in] mu The repair rate (hourly).
Definition at line 178 of file exponential.cc.
scram::mef::PeriodicTest::PeriodicTest (const ExpressionPtr & lambda, const ExpressionPtr & lambda_test, const ExpressionPtr & mu, const ExpressionPtr & tau, const ExpressionPtr & theta, const ExpressionPtr & gamma, const ExpressionPtr & test_duration, const ExpressionPtr & available_at_test, const ExpressionPtr & sigma, const ExpressionPtr & omega, const ExpressionPtr & time)
Fully parametrized periodic-test description.
Parameters
[in] lambda The failure rate (hourly) when functioning.
[in] tau The time between tests in hours.
[in] theta The time before the first test in hours.
[in] time The current mission time in hours.
[in] mu The repair rate (hourly).
[in] lambda_test The component failure rate while under test.
[in] gamma The failure probability due to or at test start.
[in] test_duration The duration of the test phase.
[in] available_at_test Indicator of component availability at test.
[in] sigma The probability of failure detection upon test.
[in] omega The probability of failure at restart after repair/test.
Definition at line 184 of file exponential.cc.
References THROW_INVALID_PROBABILITY, THROW_NEGATIVE_EXPR, and THROW_NON_POSITIVE_EXPR.
Member Function Documentation
void scram::mef::PeriodicTest::Validate () const inline override virtual
Validates the expression.
This late validation is due to parameters that are defined late.
Exceptions
InvalidArgument The arguments are invalid for setup.
Reimplemented from scram::mef::Expression.
Definition at line 154 of file exponential.h.
double scram::mef::PeriodicTest::Mean () inline override virtual noexcept
Returns
The mean value of this expression.
Implements scram::mef::Expression.
Definition at line 155 of file exponential.h.
double scram::mef::PeriodicTest::Max () inline override virtual noexcept
Returns
Maximum value of this expression.
Reimplemented from scram::mef::Expression.
Definition at line 156 of file exponential.h.
double scram::mef::PeriodicTest::Min () inline override virtual noexcept
Returns
Minimum value of this expression.
Reimplemented from scram::mef::Expression.
Definition at line 157 of file exponential.h.
References scram::mef::ExponentialExpression::Mean(), scram::mef::Expression::Sample(), and scram::mef::ExponentialExpression::Validate().
The documentation for this class was generated from the following files:
exponential.h
exponential.cc