scram::mef::CcfGroup Class Reference
scram::mef::CcfGroup Class Reference abstract
Abstract base class for all common cause failure models.
#include <ccf_group.h>
Public Member Functions
const std::vector< BasicEventPtr > & members () const
void AddMember (const BasicEventPtr &basic_event)
Adds a basic event into this CCF group.
void AddDistribution (const ExpressionPtr &distr)
Adds the distribution that describes the probability of basic events in this CCF group.
void AddFactor (const ExpressionPtr &factor, boost::optional< int > level={})
Adds a CCF factor for the specified model.
void Validate () const
Validates the setup for the CCF model and group.
void ApplyModel ()
Processes the given factors and members to create common cause failure probabilities and new events that can replace the members in a fault tree.
Public Member Functions inherited from scram::mef::Id
Id (std::string name, std::string base_path="", RoleSpecifier role=RoleSpecifier::kPublic)
Constructs an element with an original name.
const std::string & id () const
Public Member Functions inherited from scram::mef::Element
Element (std::string name)
Constructs an element with an original name.
const std::string & name () const
const std::string & label () const
void label (std::string new_label)
Sets the label.
void AddAttribute (Attribute attr)
Adds an attribute to the attribute map.
bool HasAttribute (const std::string &name) const
Checks if the element has a given attribute.
const Attribute & GetAttribute (const std::string &name) const
Public Member Functions inherited from scram::mef::Role
Role (RoleSpecifier role=RoleSpecifier::kPublic, std::string base_path="")
Sets the role of an element upon creation.
RoleSpecifier role () const
const std::string & base_path () const
Protected Types
using ExpressionMap = std::vector< std::pair< int, ExpressionPtr >>
Mapping expressions and their application levels.
Protected Member Functions
const ExpressionPtr & distribution () const
const ExpressionMap & factors () const
Detailed Description
Abstract base class for all common cause failure models.
Definition at line 89 of file ccf_group.h.
Member Function Documentation
const std::vector<BasicEventPtr>& scram::mef::CcfGroup::members () const inline
Returns
Members of the CCF group with original names as keys.
Definition at line 96 of file ccf_group.h.
References scram::mef::BasicEvent::Validate().
Referenced by ApplyModel(), and scram::Reporter::ReportCalculatedQuantity< core::RiskAnalysis >().
void scram::mef::CcfGroup::AddMember (const BasicEventPtr & basic_event)
Adds a basic event into this CCF group.
This function asserts that each basic event has unique string id.
Parameters
[in] basic_event A member basic event.
Exceptions
DuplicateArgumentError The basic event is already in the group.
IllegalOperation The probability distribution or factors for this CCF group are already defined. No more members are accepted.
Definition at line 37 of file ccf_group.cc.
References scram::mef::Element::name().
Referenced by scram::mef::Initializer::Extractor< T,-1 >::operator()().
void scram::mef::CcfGroup::AddDistribution (const ExpressionPtr & distr)
Adds the distribution that describes the probability of basic events in this CCF group.
All basic events should be added as members before defining their probabilities. No more basic events can be added after this function.
Parameters
[in] distr The probability distribution of this group.
Exceptions
ValidationError Not enough members.
LogicError The distribution has already been defined.
Definition at line 52 of file ccf_group.cc.
References scram::mef::Element::name().
Referenced by scram::mef::Initializer::Define().
void scram::mef::CcfGroup::AddFactor (const ExpressionPtr & factor, boost::optional< int > level = {})
Adds a CCF factor for the specified model.
All basic events should be added as members before defining the CCF factors. No more basic events can be added after this function.
Parameters
[in] factor A factor for the CCF model.
[in] level The level of the passed factor.
Exceptions
ValidationError The level is invalid.
RedefinitionError The factor for the level already exists.
LogicError The level is not positive, or the CCF group members are undefined.
Definition at line 65 of file ccf_group.cc.
References scram::mef::Element::name().
Referenced by scram::mef::Initializer::Extractor< T,-1 >::operator()().
void scram::mef::CcfGroup::Validate () const
Validates the setup for the CCF model and group.
Checks if the provided distribution is between 0 and 1.
This check must be performed before validating basic events that are members of this CCF group to give more precise error messages.
Exceptions
ValidationError There is an issue with the setup.
LogicError The primary distribution, event, factors are not set.
Definition at line 100 of file ccf_group.cc.
References scram::mef::Element::name().
void scram::mef::CcfGroup::ApplyModel ()
Processes the given factors and members to create common cause failure probabilities and new events that can replace the members in a fault tree.
Precondition
The CCF is validated.
Definition at line 142 of file ccf_group.cc.
References distribution(), factors(), scram::mef::ConstantExpression::kOne, members(), and scram::mef::Element::name().
const ExpressionPtr& scram::mef::CcfGroup::distribution () const inline protected
Returns
The probability distribution of the events.
Definition at line 158 of file ccf_group.h.
Referenced by ApplyModel().
const ExpressionMap& scram::mef::CcfGroup::factors () const inline protected
Returns
CCF factors of the model.
Definition at line 161 of file ccf_group.h.
Referenced by ApplyModel().
The documentation for this class was generated from the following files:
ccf_group.h
ccf_group.cc