scram::mef::MissionTime Class Reference
scram::mef::MissionTime Class Reference
The special parameter for system mission time.
#include <parameter.h>
Public Member Functions
MissionTime (double time=0, Units unit=kHours)
Units unit () const
void value (double time)
Changes the mission time value.
double Min () noexceptoverride
double Mean () noexceptoverride
bool IsDeviate () noexceptoverride
Determines if the value of the expression contains deviate expressions.
Public Member Functions inherited from scram::mef::Expression
Expression (std::vector< ExpressionPtr > args={})
Constructor for use by derived classes to register their arguments.
const std::vector< ExpressionPtr > & args () const
virtual void Validate () const
Validates the expression.
double Sample () noexcept
virtual void Reset () noexcept
This routine resets the sampling to get new values.
virtual double Max () noexcept
Additional Inherited Members
Protected Member Functions inherited from scram::mef::Expression
void AddArg (const ExpressionPtr &arg)
Registers an additional argument expression.
Detailed Description
The special parameter for system mission time.
Definition at line 55 of file parameter.h.
Constructor & Destructor Documentation
scram::mef::MissionTime::MissionTime (double time = 0, Units unit = kHours) explicit
Parameters
[in] time The mission time.
[in] unit The unit of the given time argument.
Exceptions
LogicError The time value is negative.
Definition at line 28 of file parameter.cc.
References value().
Member Function Documentation
Units scram::mef::MissionTime::unit () const inline
Returns
The unit of the system mission time.
Definition at line 64 of file parameter.h.
References value().
void scram::mef::MissionTime::value (double time)
Changes the mission time value.
Parameters
[in] time The mission time in hours.
Exceptions
LogicError The time value is negative.
Definition at line 34 of file parameter.cc.
Referenced by scram::core::McubCalculator::Calculate(), MissionTime(), and unit().
double scram::mef::MissionTime::Min () inline override virtual noexcept
Returns
Minimum value of this expression.
Reimplemented from scram::mef::Expression.
Definition at line 73 of file parameter.h.
double scram::mef::MissionTime::Mean () inline override virtual noexcept
Returns
The mean value of this expression.
Implements scram::mef::Expression.
Definition at line 74 of file parameter.h.
Referenced by scram::core::McubCalculator::Calculate().
bool scram::mef::MissionTime::IsDeviate () inline override virtual noexcept
Determines if the value of the expression contains deviate expressions.
The default logic is to check arguments with uncertainties for sampling. Derived expression classes must decide if they don't have arguments, or if they are random deviates.
Returns
true if the expression's value deviates from its mean.
false if the expression's value not need sampling.
Warning
Improper registration of arguments may yield silent failure.
Reimplemented from scram::mef::Expression.
Definition at line 75 of file parameter.h.
The documentation for this class was generated from the following files:
parameter.h
parameter.cc