scram::mef::LogNormalDeviate Class Reference
scram::mef::LogNormalDeviate Class Reference
Log-normal distribution.
#include <random_deviate.h>
Public Member Functions
LogNormalDeviate (const ExpressionPtr &mean, const ExpressionPtr &ef, const ExpressionPtr &level)
The log-normal deviate parametrization with its expected value and error factor of certain confidence level.
LogNormalDeviate (const ExpressionPtr &mu, const ExpressionPtr &sigma)
The parametrization with underlying normal distribution parameters.
void Validate () const override
Validates the expression.
double Mean () noexceptoverride
double Max () noexceptoverride
99.9 percentile estimate.
double Min () noexceptoverride
Public Member Functions inherited from scram::mef::RandomDeviate
bool IsDeviate () noexceptoverride
Determines if the value of the expression contains deviate expressions.
Public Member Functions inherited from scram::mef::Expression
Expression (std::vector< ExpressionPtr > args={})
Constructor for use by derived classes to register their arguments.
const std::vector< ExpressionPtr > & args () const
double Sample () noexcept
virtual void Reset () noexcept
This routine resets the sampling to get new values.
Additional Inherited Members
Protected Member Functions inherited from scram::mef::Expression
void AddArg (const ExpressionPtr &arg)
Registers an additional argument expression.
Detailed Description
Log-normal distribution.
Definition at line 95 of file random_deviate.h.
Constructor & Destructor Documentation
scram::mef::LogNormalDeviate::LogNormalDeviate (const ExpressionPtr & mean, const ExpressionPtr & ef, const ExpressionPtr & level)
The log-normal deviate parametrization with its expected value and error factor of certain confidence level.
Parameters
[in] mean The mean of the log-normal distribution not the mean of underlying normal distribution, which is parameter mu. mu is the location parameter, sigma is the scale factor. E(x) = exp(mu + sigma^2 / 2)
[in] ef The error factor of the log-normal distribution. EF = exp(z_alpha * sigma)
[in] level The confidence level.
Definition at line 73 of file random_deviate.cc.
scram::mef::LogNormalDeviate::LogNormalDeviate (const ExpressionPtr & mu, const ExpressionPtr & sigma)
The parametrization with underlying normal distribution parameters.
Parameters
[in] mu The mean of the normal distribution.
[in] sigma The standard deviation of the normal distribution.
Definition at line 79 of file random_deviate.cc.
References scram::Random::LogNormalGenerator().
Member Function Documentation
void scram::mef::LogNormalDeviate::Validate () const inline override virtual
Validates the expression.
This late validation is due to parameters that are defined late.
Exceptions
InvalidArgument The arguments are invalid for setup.
Reimplemented from scram::mef::Expression.
Definition at line 118 of file random_deviate.h.
double scram::mef::LogNormalDeviate::Mean () inline override virtual noexcept
Returns
The mean value of this expression.
Implements scram::mef::Expression.
Definition at line 119 of file random_deviate.h.
References scram::mef::Expression::Max().
double scram::mef::LogNormalDeviate::Min () inline override virtual noexcept
Returns
Minimum value of this expression.
Reimplemented from scram::mef::Expression.
Definition at line 123 of file random_deviate.h.
References scram::mef::Expression::Validate().
The documentation for this class was generated from the following files:
random_deviate.h
random_deviate.cc