scram::mef::Model Class Reference
scram::mef::Model Class Reference
This class represents a risk analysis model.
#include <model.h>
Public Member Functions
Model (std::string name="")
Creates a model container.
void BindEvent (const std::string &entity_reference, const std::string &base_path, Formula *formula)
Binds a formula with its argument event.
const ElementTable< EventTreePtr > & event_trees () const
const ElementTable< SequencePtr > & sequences () const
const ElementTable< FaultTreePtr > & fault_trees () const
const IdTable< ParameterPtr > & parameters () const
const std::shared_ptr< MissionTime > & mission_time () const
const IdTable< HouseEventPtr > & house_events () const
const IdTable< BasicEventPtr > & basic_events () const
const IdTable< GatePtr > & gates () const
const IdTable< CcfGroupPtr > & ccf_groups () const
void Add (EventTreePtr element)
Adds MEF constructs into the model container.
void Add (const SequencePtr &element)
Adds MEF constructs into the model container.
void Add (FaultTreePtr element)
Adds MEF constructs into the model container.
void Add (const ParameterPtr &element)
Adds MEF constructs into the model container.
void Add (const HouseEventPtr &element)
Adds MEF constructs into the model container.
void Add (const BasicEventPtr &element)
Adds MEF constructs into the model container.
void Add (const GatePtr &element)
Adds MEF constructs into the model container.
void Add (const CcfGroupPtr &element)
Adds MEF constructs into the model container.
ParameterPtr GetParameter (const std::string &entity_reference, const std::string &base_path)
Finds an entity (parameter, basic and house event, gate) from a reference.
HouseEventPtr GetHouseEvent (const std::string &entity_reference, const std::string &base_path)
Finds an entity (parameter, basic and house event, gate) from a reference.
BasicEventPtr GetBasicEvent (const std::string &entity_reference, const std::string &base_path)
Finds an entity (parameter, basic and house event, gate) from a reference.
GatePtr GetGate (const std::string &entity_reference, const std::string &base_path)
Finds an entity (parameter, basic and house event, gate) from a reference.
Public Member Functions inherited from scram::mef::Element
Element (std::string name)
Constructs an element with an original name.
const std::string & name () const
const std::string & label () const
void label (std::string new_label)
Sets the label.
void AddAttribute (Attribute attr)
Adds an attribute to the attribute map.
bool HasAttribute (const std::string &name) const
Checks if the element has a given attribute.
const Attribute & GetAttribute (const std::string &name) const
Static Public Attributes
static const char kDefaultName [] = "unnamed-model"
Detailed Description
This class represents a risk analysis model.
Definition at line 45 of file model.h.
Constructor & Destructor Documentation
scram::mef::Model::Model (std::string name = "") explicit
Creates a model container.
Parameters
[in] name The optional name for the model.
Exceptions
InvalidArgument The name is malformed.
Definition at line 31 of file model.cc.
Member Function Documentation
const ElementTable<EventTreePtr>& scram::mef::Model::event_trees () const inline
Returns
Defined constructs in the model.
Definition at line 62 of file model.h.
Referenced by scram::Reporter::ReportCalculatedQuantity< core::RiskAnalysis >().
const ElementTable<SequencePtr>& scram::mef::Model::sequences () const inline
Returns
Defined constructs in the model.
Definition at line 63 of file model.h.
const ElementTable<FaultTreePtr>& scram::mef::Model::fault_trees () const inline
Returns
Defined constructs in the model.
Definition at line 64 of file model.h.
Referenced by scram::Reporter::ReportCalculatedQuantity< core::RiskAnalysis >().
const IdTable<ParameterPtr>& scram::mef::Model::parameters () const inline
Returns
Defined constructs in the model.
Definition at line 65 of file model.h.
Referenced by scram::Reporter::ReportCalculatedQuantity< core::RiskAnalysis >().
const std::shared_ptr<MissionTime>& scram::mef::Model::mission_time () const inline
Returns
Defined constructs in the model.
Definition at line 68 of file model.h.
const IdTable<HouseEventPtr>& scram::mef::Model::house_events () const inline
Returns
Defined constructs in the model.
Definition at line 71 of file model.h.
Referenced by scram::Reporter::ReportCalculatedQuantity< core::RiskAnalysis >().
const IdTable<BasicEventPtr>& scram::mef::Model::basic_events () const inline
Returns
Defined constructs in the model.
Definition at line 74 of file model.h.
Referenced by scram::Reporter::ReportCalculatedQuantity< core::RiskAnalysis >().
const IdTable<GatePtr>& scram::mef::Model::gates () const inline
Returns
Defined constructs in the model.
Definition at line 77 of file model.h.
Referenced by scram::Reporter::ReportCalculatedQuantity< core::RiskAnalysis >().
const IdTable<CcfGroupPtr>& scram::mef::Model::ccf_groups () const inline
Returns
Defined constructs in the model.
Definition at line 78 of file model.h.
References Add(), BindEvent(), GetBasicEvent(), scram::mef::GetFullPath(), GetGate(), GetHouseEvent(), and GetParameter().
Referenced by scram::Reporter::ReportCalculatedQuantity< core::RiskAnalysis >().
void scram::mef::Model::Add (EventTreePtr element)
Adds MEF constructs into the model container.
Parameters
[in] element An element defined in this model.
Exceptions
RedefinitionError The element is already defined in the model.
Definition at line 35 of file model.cc.
Referenced by ccf_groups().
void scram::mef::Model::Add (const SequencePtr & element)
Adds MEF constructs into the model container.
Parameters
[in] element An element defined in this model.
Exceptions
RedefinitionError The element is already defined in the model.
Definition at line 42 of file model.cc.
void scram::mef::Model::Add (FaultTreePtr element)
Adds MEF constructs into the model container.
Parameters
[in] element An element defined in this model.
Exceptions
RedefinitionError The element is already defined in the model.
Definition at line 49 of file model.cc.
void scram::mef::Model::Add (const ParameterPtr & element)
Adds MEF constructs into the model container.
Parameters
[in] element An element defined in this model.
Exceptions
RedefinitionError The element is already defined in the model.
Definition at line 56 of file model.cc.
void scram::mef::Model::Add (const HouseEventPtr & element)
Adds MEF constructs into the model container.
Parameters
[in] element An element defined in this model.
Exceptions
RedefinitionError The element is already defined in the model.
Definition at line 62 of file model.cc.
void scram::mef::Model::Add (const BasicEventPtr & element)
Adds MEF constructs into the model container.
Parameters
[in] element An element defined in this model.
Exceptions
RedefinitionError The element is already defined in the model.
Definition at line 70 of file model.cc.
void scram::mef::Model::Add (const GatePtr & element)
Adds MEF constructs into the model container.
Parameters
[in] element An element defined in this model.
Exceptions
RedefinitionError The element is already defined in the model.
Definition at line 78 of file model.cc.
void scram::mef::Model::Add (const CcfGroupPtr & element)
Adds MEF constructs into the model container.
Parameters
[in] element An element defined in this model.
Exceptions
RedefinitionError The element is already defined in the model.
Definition at line 86 of file model.cc.
ParameterPtr scram::mef::Model::GetParameter (const std::string & entity_reference, const std::string & base_path)
Finds an entity (parameter, basic and house event, gate) from a reference.
The reference is case sensitive and can contain an identifier, full path, or local path.
Parameters
[in] entity_reference Reference string to the entity.
[in] base_path The series of containers indicating the scope.
Returns
Pointer to the entity found by following the given reference.
Exceptions
std::out_of_range The entity cannot be found.
Definition at line 92 of file model.cc.
Referenced by ccf_groups().
HouseEventPtr scram::mef::Model::GetHouseEvent (const std::string & entity_reference, const std::string & base_path)
Finds an entity (parameter, basic and house event, gate) from a reference.
The reference is case sensitive and can contain an identifier, full path, or local path.
Parameters
[in] entity_reference Reference string to the entity.
[in] base_path The series of containers indicating the scope.
Returns
Pointer to the entity found by following the given reference.
Exceptions
std::out_of_range The entity cannot be found.
Definition at line 97 of file model.cc.
Referenced by ccf_groups().
BasicEventPtr scram::mef::Model::GetBasicEvent (const std::string & entity_reference, const std::string & base_path)
Finds an entity (parameter, basic and house event, gate) from a reference.
The reference is case sensitive and can contain an identifier, full path, or local path.
Parameters
[in] entity_reference Reference string to the entity.
[in] base_path The series of containers indicating the scope.
Returns
Pointer to the entity found by following the given reference.
Exceptions
std::out_of_range The entity cannot be found.
Definition at line 102 of file model.cc.
Referenced by ccf_groups().
GatePtr scram::mef::Model::GetGate (const std::string & entity_reference, const std::string & base_path)
Finds an entity (parameter, basic and house event, gate) from a reference.
The reference is case sensitive and can contain an identifier, full path, or local path.
Parameters
[in] entity_reference Reference string to the entity.
[in] base_path The series of containers indicating the scope.
Returns
Pointer to the entity found by following the given reference.
Exceptions
std::out_of_range The entity cannot be found.
Definition at line 107 of file model.cc.
Referenced by ccf_groups().
void scram::mef::Model::BindEvent (const std::string & entity_reference, const std::string & base_path, Formula * formula)
Binds a formula with its argument event.
This is a special handling for undefined event types with mixed roles.
Parameters
[in] entity_reference Reference string to the entity.
[in] base_path The series of containers indicating the scope.
[out] formula The host formula for the event.
Exceptions
std::out_of_range The entity cannot be found.
Definition at line 144 of file model.cc.
References BIND_EVENT.
Referenced by ccf_groups().
Member Data Documentation
const char scram::mef::Model::kDefaultName = "unnamed-model" static
Todo:
Only Model is allowed to have an optional name, while all other Elements require names.
An empty name is an error for Element class invariants as well. This leads to a nasty magic string based optional name for a model.
Definition at line 51 of file model.h.
Referenced by scram::Reporter::ReportCalculatedQuantity< core::RiskAnalysis >().
The documentation for this class was generated from the following files:
model.h
model.cc